# R Cheat Sheet

In [2]:
# This is a comment
a <- 1 #assigning a value to a variabele
a

[1] 1

## Datatypes
### Characters
String values are known as characters in R.

In [6]:
#For assignment you can use single quates and double quotes.
char1 <- 'Hello'
char2 <- "World!"
#Concatenating strings
char3 <- paste(char1, char2, sep=" ")
print(char3)
class(char3)

[1] "Hello World!"


[1] "character"

### Numeric
Integers and decimal numbers belong to the numeric class

In [11]:
num1 <- 5
num2 <- 7
# +, -, *, / work as expected
num2 / num1

[1] 1.4

In [12]:
#modulus
num2 %% num1

[1] 2

In [13]:
#integer divide
num2 %/% num1

[1] 1

### Logical
Logical values are booleans.

In [14]:
logical1 <- TRUE # TRUE and FALSE must be all capital letters
logical2 <- F    # T and F for TRUE and FALSE are also valid but again must be capital
class(logical2)

[1] "logical"

### Vectors
A vector is a 1 dimensional array that can hold character, numeric, or logical data elements of one type. This means that one vector can not have character and numeric data elements. If you define a vector with mixed data elements R will convert the elements in the array to force everything to be of the same data type. 

In [15]:
# Create a vector of numeric elements
nvec <- c(1,2,3,4,5)
# Create a vector of character elements
cvec <- c('a', 'b', 'c')
# Create a vector of logical elements
lvec <- c(TRUE, FALSE)
class(lvec)

[1] "logical"

In [16]:
#named vectors
celcius <- c(9,7,6,5,4,7,11)
days <- c('Mon','Tue','Wed','Thu','Fri','Sat','Sun')
names(celcius) <- days
celcius

Mon Tue Wed Thu Fri Sat Sun 
  9   7   6   5   4   7  11

In [22]:
# working with vectors
v1 <- c(1,2,3)
v2 <- c(5,6,7)
print(v1+v2)
print(v1*v2)
print(v2-v1)
print(v2/v1)

[1]  6  8 10
[1]  5 12 21
[1] 4 4 4
[1] 5.000000 3.000000 2.333333


In [23]:
sum(v1)

[1] 6

In [29]:
# Product of elements
prod(v1)

[1] 6

In [30]:
# Standard Deviation
v3 <- c(16,50,75,5,38,22)
sd(v3)

[1] 25.53951

In [31]:
#Variance
var(v3)

[1] 652.2667

In [32]:
max(v3)

[1] 75

In [33]:
min(v3)

[1] 5

In [34]:
mean(v3)

[1] 34.33333

In [35]:
# Grab second element, Unlike most other programming languages indexing starts at 1
v1[2]

[1] 2

In [36]:
# grab multiple items
v2[c(1,3)]

[1] 5 7

In [37]:
v4 <- c(1,2,3,4,5,6,7,8,9,10)
v4[2:4]

[1] 2 3 4

In [38]:
names(v4) <- c('a','b','c','d','e','f','g','i','j','k')
v4[c('b','k','d')]

b  k  d 
 2 10  4

In [39]:
v4>4

a     b     c     d     e     f     g     i     j     k 
FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [41]:
v4[v4>=4]

d  e  f  g  i  j  k 
 4  5  6  7  8  9 10

### Matrices

In [44]:
#create a matrix
v <- 1:20
matrix(v,byrow=TRUE,nrow=4)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5  
[2,]  6    7    8    9   10  
[3,] 11   12   13   14   15  
[4,] 16   17   18   19   20

In [48]:
week1 <- c(5024, 6743, 4999, 5070, 5433)
week2 <- c(6349, 5923, 4877, 4020, 7389)
sales <- c(week1,week2)
sales.matrix <- matrix(sales,byrow=TRUE,nrow=2)
sales.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 5024 6743 4999 5070 5433
[2,] 6349 5923 4877 4020 7389

In [49]:
days <- c('Mon','Tue','Wed','Thu','Fri')
weeks.names <- c('Week1','Week2')
colnames(sales.matrix) <- days
rownames(sales.matrix) <- weeks.names
sales.matrix

Mon  Tue  Wed  Thu  Fri 
Week1 5024 6743 4999 5070 5433
Week2 6349 5923 4877 4020 7389

In [50]:
mat <- matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [51]:
#multipliyng, dividing, power works like expected example
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [53]:
#comparison
mat > 23

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[3,] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [54]:
#you can also add, subtract,multiply and divide matrices. This works on element by element basis
# note on multiplication this is not the same as matrix multiplication in a mathematical sense
mat*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

In [56]:
# True Matrix Multiplication
mat2 <- matrix(1:25, nrow=5)
mat2 %*% mat2

[,1] [,2] [,3] [,4] [,5]
[1,] 215  490   765 1040 1315
[2,] 230  530   830 1130 1430
[3,] 245  570   895 1220 1545
[4,] 260  610   960 1310 1660
[5,] 275  650  1025 1400 1775

In [57]:
colSums(sales.matrix)

Mon   Tue   Wed   Thu   Fri 
11373 12666  9876  9090 12822

In [58]:
rowSums(sales.matrix)

Week1 Week2 
27269 28558

In [59]:
rowMeans(sales.matrix)

Week1  Week2 
5453.8 5711.6

In [60]:
colMeans(sales.matrix)

Mon    Tue    Wed    Thu    Fri 
5686.5 6333.0 4938.0 4545.0 6411.0

In [61]:
week3 <- c(5792,4311,6619,7001,5522)
sales.matrix <- rbind(sales.matrix,week3)
sales.matrix

Mon  Tue  Wed  Thu  Fri 
Week1 5024 6743 4999 5070 5433
Week2 6349 5923 4877 4020 7389
week3 5792 4311 6619 7001 5522

In [62]:
avg <- rowMeans(sales.matrix)
sales.matrix <- cbind(sales.matrix,avg)
sales.matrix

Mon  Tue  Wed  Thu  Fri  avg   
Week1 5024 6743 4999 5070 5433 5453.8
Week2 6349 5923 4877 4020 7389 5711.6
week3 5792 4311 6619 7001 5522 5849.0

In [63]:
#get the first column
mat[,1]

[1]  1 11 21 31 41

In [65]:
#get the second row
mat[2,]

[1] 11 12 13 14 15 16 17 18 19 20

In [66]:
#the last two columns
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [67]:
mat[2:3,5:6]

[,1] [,2]
[1,] 15   16  
[2,] 25   26

In [68]:
# get a small rectangle in the middle
mat[2:4,4:7]

[,1] [,2] [,3] [,4]
[1,] 14   15   16   17  
[2,] 24   25   26   27  
[3,] 34   35   36   37